name: Build Daily Book
on:
  workflow_dispatch:
  schedule:
    - cron: "3 16 * * *"
jobs:
  build-deploy:
    concurrency: build-daily-book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('cli.ts') }}
      - name: Get Yestoday Beijin Day
        id: date
        run: |
          echo "::set-output name=yesterday::$(deno run cli.ts --yesterday --key)"
      - run: make install
      - name: Build yesterday book
        id: build
        run: make yesterdaymail
        continue-on-error: true
        env:
          MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
          MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}
          JOURNAL_PATH: ./blog
          JOURNAL_URL: https://www.owenyoung.com/blog/journals/
      - name: make release if build success
        if: steps.build.outcome == 'success'
        uses: "softprops/action-gh-release@v1"
        env:
          YESTERDAY: 
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          tag_name: "daily-${{ steps.date.outputs.yesterday }}"
          generate_release_notes: false
          body: |
            Visit [Online](https://clip-template.vercel.app/).
          files: |
            ./dist/*/*.epub
            ./dist/*/*.zip
